COLUNAS_CAMPANHAS = {
    "noCampanha": "",
    "deCampanha": "",
    "nuAnomesInicio": "",
    "nuAnoMesFim": "",
    "deImagemCampanha": "",
    # "delogoCampanha": "",
    "deBackgroundCampanha": "",
    "dhCriacao": "",
    "dhAlteracao": "",
    "idSituacaoCampanha": "",
    "idTipoCampanha": "",
    "icApuracaoMensal": "",
    "dtFimApuracao": "",
    "idTipoParticipante": "",
    "icEmAtualizacao": "",
}
PRODUTOS = [
    "Prestamista",
    "Rapidex",
    "Residencial",
    "Capitalização",
    "Consórcio",
    "Vida",
    "Prestamista",
]
REDES = [
    "Todas as Redes",
    "Varejo Full",
    "Varejo (Agro)",
    "Varejo (Digital)",
    "Varejo (Private)",
    "Varejo (CVP)",
    "Atacado Full",
    "Atacado Sunco",
    "Atacado Sumep",
    "Parceiros Varejo",
    "Lotérico Varejo",
    "CCA Varejo",
    "Varejo/Digital",
    "Varejo/Digital/Agro",
    "Varejo/Agro",
]
